/**
 * @file i2c_temp.c
 * @author Simon Offenberger
 * @brief I2C Temperature Sensor Project which indicates a Alert via LED4 and shows the current temperature on the LCD.
 * @version 1.0
 * @date 2026-03-09
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "board_led.h"
#include "sysdelay.h"
#include "i2c_temp.h"
#include "board_MCP_temp.h"
#include "Lcd.h"
#include <stdio.h>

// includes for STM32F0xx Standard Peripheral Library
#include "stm32f0xx.h"
#include "stm32f0xx_gpio.h"
#include "stm32f0xx_exti.h"
#include "stm32f0xx_syscfg.h"
#include "stm32f0xx_rcc.h"

/**
 * @brief  Configures EXTI line 4 for MCP9800 alert interrupt on PD4.
 */
void Alert_Initialize_EXTI(void)
{
  // Enable peripheral clocks
  // Peripherals are not accessible until their clocks are enabled.
  // SYSCFG is needed to map EXTI lines to GPIO pins !
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
  RCC_AHBPeriphClockCmd(RCC_AHBENR_GPIODEN, ENABLE);

  GPIO_InitTypeDef initStruct;

  // Load default values into structure
  GPIO_StructInit(&initStruct);

  // Configure alert input pin for external interrupt
  initStruct.GPIO_Pin = GPIO_Pin_4;
  initStruct.GPIO_Mode = GPIO_Mode_IN;
  initStruct.GPIO_PuPd = GPIO_PuPd_UP; // Alert pin is active low, so we use pull-up (external PU also populated)
  GPIO_Init(GPIOD, &initStruct);

  // Connect EXTI lines to GPIO pins
  SYSCFG_EXTILineConfig(EXTI_PortSourceGPIOD, EXTI_PinSource4); // EXTI4 -> PD4

  // Configure EXTI lines
  EXTI_InitTypeDef extiInitStruct;
  extiInitStruct.EXTI_Line = EXTI_Line4;
  extiInitStruct.EXTI_Mode = EXTI_Mode_Interrupt;
  extiInitStruct.EXTI_Trigger = EXTI_Trigger_Rising_Falling; // Interrupt on both edge (alert asserted)
  extiInitStruct.EXTI_LineCmd = ENABLE;
  EXTI_Init(&extiInitStruct);

  // Enable interrupt request in NVIC
  NVIC_EnableIRQ(EXTI4_15_IRQn);
}

/**
 * @brief  Handles EXTI Line4 interrupt generated by MCP9800 alert.
 */
void EXTI4_15_IRQHandler(void)
{
  // Check if EXTI Line4 has a pending interrupt.
  if (EXTI->PR & EXTI_PR_PR4)
  {
    // Clear the EXTI Line4 pending bit no read modify write!!!
    // Because it would reset another pending flag as well!
    // 1 written to the pending register clears the pending bit
    EXTI->PR = EXTI_PR_PR4;

    // Set LED to signal Alert
    if(GPIO_ReadInputDataBit(GPIOD, GPIO_Pin_4) == Bit_RESET){
      LED_On(LED4);
    }
    else{
      LED_Off(LED4);
    }
  }
}

/**
 * @brief Main function for the Project I2C Temperature Sensor Exercise 8.
 */
void main_I2C_Temp()
{
  // Enable global interrupts
  __enable_irq();

  // Initialize Peripheral
  LED_Initialize();
  Lcd_Initialize();
  Lcd_Fill(0, 0, LCD_WIDTH, LCD_HEIGHT, RGB565_WHITE);

  // Initialize MCP9800 temperature sensor with user-selected configuration.
  const MCP9800_Init_StructTypeDef mcp9800Init = {
      .Shutdown_Mode = MCP9800_SHUTDOWN_MODE_DISABLE,
      .Alert_Mode = MCP9800_COMPARATOR_MODE,
      .Alert_Polarity = MCP9800_ALERT_POLARITY_ACTIVE_LOW,
      .Fault_Queue = MCP9800_FAULT_QUEUE_1,
      .Resolution = MCP9800_ADC_RESOLUTION_0_5C,
      .One_Shot = MCP9800_ONE_SHOT_DISABLE};

  MCP9800_Temp_HandleTypeDef MCP9800_Handle = {
      .i2c_handle = I2C_RTC_TEMP,
      .adr = MCP9800_SLAVE_ADDRESS,
      .init = mcp9800Init};

  MCP9800_Temp_Init(&MCP9800_Handle);

  // Program alert upper threshold and hysteresis values.
  MCP9800_Temp_Set_TSET(&MCP9800_Handle, TEMP_ALERT_THRESHOLD);
  MCP9800_Temp_Set_THYST(&MCP9800_Handle, TEMP_ALERT_HYSTERESIS);

  // Initialize EXTI for Alert pin to signal overtemperature events via LED4.
  Alert_Initialize_EXTI();

  while (1)
  {
    float temp = 0;

    // Periodically poll sensor temperature via I2C.
    MCP9800_Temp_ReadTemp(&MCP9800_Handle, &temp);

    char temp_str[LCD_TEXT_BUFFER_SIZE] = {0};

    // Update current temperature on LCD.
    snprintf(temp_str, LCD_TEXT_BUFFER_SIZE, "Temperatur %3.1fC  ", temp);

    Lcd_Print(0, 0, temp_str, RGB565_BLACK, RGB565_WHITE, &Consolas);

    SysDelay_Delay(I2C_POLL_INTERVAL_MS);
  }
}